version: '3.8'

services:
  app:
    build:
      context: ../web_app
      dockerfile: Dockerfile.app
    environment:
      - FLASK_ENV=production
    networks:
      - app-network
    deploy:
      replicas: 2

  nginx:
    image: nginx:alpine
    ports:
      - "8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge